PLT-5314 - Add Upload Document Card Component
beforeyoubid/ui-lib pull request #23
Opened 2023-07-16 23:29 UTC by akramimtiaz-byb

https://beforeyoubid.atlassian.net/browse/PLT-5314

2023-07-19 09:39 UTC, bailey-byb requested changes
few comments but overall looks good. might be worth separating each state into a unique file instead of the styles file... leave it with to you to decide though

2023-07-19 09:39 UTC, bailey-byb commented on src/components/UploadDocumentCard/styles.tsx
> +const StyledLinearProgress = styled(LinearProgress)(({ theme }: { theme: Theme }) => ({
you dont need the theme typing here

2023-07-20 08:01 UTC, akramimtiaz-byb commented
> few comments but overall looks good. might be worth separating each state into a unique file instead of the styles file... leave it with to you to decide though

- comments addressed
- components moved into separate files

2023-07-20 08:22 UTC, ben-byb approved these changes
🤷‍♂️

2023-07-20 08:27 UTC, merged